sudo: required

services:
  - docker

language: node_js
node_js:
  - 13

# before_install:
#   - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

script:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_API_KEY" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
  # - docker run huczk/realworld-ts-ql yarn test
  - docker-compose up -d
  - cd ./server && sh utils/wait-for-sql.sh && yarn test
  # - docker-compose exec web yarn test
  - docker build -t huczk/realworld-ts-ql ./server  - docker tag huczk/realworld-ts-ql:latest registry.heroku.com/$HEROKU_APP/web

deploy:
  provider: script
  script:
    # push to dockerhub & heroku
    docker push huczk/realworld-ts-ql;
    docker push registry.heroku.com/$HEROKU_APP/web;
    heroku container:release web --app $HEROKU_APP
  on:
    branch: master
