version: "3.7"

services:
  db:
    image: "mysql:8"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./.db:/var/lib/mysql
    restart: unless-stopped
    env_file:
      - ./envdev/mysql.env

  web:
    image: "node:13"
    depends_on:
      - db
    working_dir: /app
    volumes:
      - ./server:/app
    ports:
      - "3000:3000"
    command: 'bash -c "yarn && yarn dev"'
    env_file:
      - ./envdev/mysql.env
      - ./envdev/node.env
